---
title: "Prework"  # Add a page title.
summary: "Your pre-workshop to do list"  # Add a page description.
date: "2020-01-01T00:00:00Z"  # Add today's date.
---


Thank you for enrolling in our workshop, Introduction to Machine Learning with the Tidyverse. To prepare for the workshop:

Please bring a laptop to class that has the following installed:

* A recent version of R (>=3.6.0), which is available for free at <https://cran.r-project.org/>

* A recent version of RStudio Desktop (>=1.2.1500), available for free at <https://www.rstudio.com/download> (RStudio Desktop Open Source License)

* The R packages we will use, which you can install by connecting to the internet, opening RStudio, and running at the command line:

    ```{r eval = FALSE}
    install.packages(c("tidyverse", "tidymodels", 
                       "remotes", "rpart.plot", "rattle", 
                       "vip", "AmesHousing", "kknn", 
                       "rpart", "ranger", "partykit"))
    
    # and
    
    remotes::install_github(
      c("tidymodels/workflows", 
        "tidymodels/tune", 
        "tidymodels/modeldata"))
    ```

And don't forget your power cord!

On the day of the class, we'll provide you with an RStudio Server Pro login that contains all of the course materials. We will use the software listed above only as an important backup should there be problems with the classroom server connection.

We look forward to meeting you,

Alison